"""Add categories

Revision ID: a0a0cc91318c
Revises: ff0a7f02baa9
Create Date: 2025-07-19 15:20:28.017633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a0cc91318c'
down_revision: Union[str, None] = 'ff0a7f02baa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'PURCHASE', 'TRANSFER', name='categorytype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accounts', sa.Column('account_name', sa.String(length=50), nullable=True))
    op.add_column('accounts', sa.Column('account_number', sa.String(length=20), nullable=True))
    op.add_column('accounts', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('accounts', sa.Column('icon', sa.String(length=50), nullable=True))
    op.alter_column('accounts', 'account_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DEBIT_CARD', 'CREDIT_CARD', 'SAVINGS', 'INVESTMENT', 'CASH', 'OTHER', name='accounttype'),
               existing_nullable=True)
    op.alter_column('accounts', 'status',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='accountstatus'),
               existing_nullable=False)
    op.create_unique_constraint(None, 'accounts', ['account_number'])
    op.drop_column('accounts', 'name')
    op.add_column('transactions', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'category_id')
    op.add_column('accounts', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'accounts', type_='unique')
    op.alter_column('accounts', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='accountstatus'),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('accounts', 'account_type',
               existing_type=sa.Enum('DEBIT_CARD', 'CREDIT_CARD', 'SAVINGS', 'INVESTMENT', 'CASH', 'OTHER', name='accounttype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('accounts', 'icon')
    op.drop_column('accounts', 'color')
    op.drop_column('accounts', 'account_number')
    op.drop_column('accounts', 'account_name')
    op.drop_table('categories')
    # ### end Alembic commands ###
